### ISSUE TITLE
TensorFlow Object Detection Model Zoo not available anymore

### ISSUE THREAD

**Issue by russom** [udacity/CarND-Object-Detection-Lab#11]
Good day -

The previous link to TensorFlow object detection model zoo is not available anymore.

It seems that at the beginning of July TensorFlow released the model [garden](https://github.com/tensorflow/models), where can be found two object detection zoos, one for TF [V1](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md) and one for [V2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). Links should be updated.

Thanks, and regards,

M. Russo

**Comment by UAnjali** [comment]
Hi @russom,
Thanks for bringing this to our notice. We have changed the file based on your suggestion. 
Thank you
