### ISSUE TITLE
Anaconda build fail

### ISSUE THREAD

**Issue by Horki** [udacity/CarND-Object-Detection-Lab#8]
conda env create -f environment.yml

`Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package python conflicts for:
imageio==2.1.2 -> numpy -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.4.*|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
imageio==2.1.2 -> numpy -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
python==3.6
imageio==2.1.2 -> python[version='2.7.*|3.5.*|3.6.*']
jupyter -> ipykernel -> tornado[version='>=4.0'] -> certifi -> python=3.4
matplotlib -> cycler[version='>=0.10'] -> python[version='2.7.*|3.5.*|3.6.*|<3']
jupyter -> ipywidgets -> nbformat[version='>=4.2.0'] -> jsonschema[version='>=2.0,!=2.5.0'] -> functools32 -> python[version='<3']
numpy -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
pillow -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
matplotlib -> cycler[version='>=0.10'] -> six -> python=3.4
imageio==2.1.2 -> pillow -> olefile -> python
pip -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
pillow -> olefile -> python
jupyter -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
scipy -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
Package gtk2 conflicts for:
jupyter -> qtconsole -> pyqt[version='>=5.9.2,<5.10.0a0'] -> qt[version='>=4.8.6,<5.0'] -> gtk2
matplotlib -> pyqt -> qt[version='>=4.8.6,<5.0'] -> gtk2
Package tk conflicts for:
scipy -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
pillow -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
matplotlib -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
jupyter -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
matplotlib -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.10,<8.7.0a0|>=8.6.9,<8.7.0a0']
pillow -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|>=8.6.10,<8.7.0a0']
python==3.6 -> tk=8.5
imageio==2.1.2 -> pillow -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
pip -> python=3.5 -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
numpy -> python[version='>=3.5,<3.6.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package readline conflicts for:
pillow -> python[version='>=2.7,<2.8.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
jupyter -> python[version='>=2.7,<2.8.0a0'] -> readline[version='7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
matplotlib -> python[version='>=3.7,<3.8.0a0'] -> readline[version='7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
pip -> python=3.5 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
imageio==2.1.2 -> python=3.6 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
scipy -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
numpy -> python[version='>=3.5,<3.6.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
python==3.6 -> readline=6.2
Package atk conflicts for:
matplotlib -> pyqt -> qt[version='>=4.8.6,<5.0'] -> gtk2 -> atk[version='>=2.32.0,<3.0a0']
jupyter -> qtconsole -> pyqt[version='>=5.9.2,<5.10.0a0'] -> qt[version='>=4.8.6,<5.0'] -> gtk2 -> atk[version='>=2.32.0,<3.0a0']
Package ipython conflicts for:
jupyter -> ipykernel -> ipython[version='>=4.0|>=4.0.0|>=5.0']
Package sqlite conflicts for:
pillow -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
pip -> python=3.5 -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
numpy -> python[version='>=3.5,<3.6.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
imageio==2.1.2 -> python=3.6 -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
jupyter -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='3.20.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
matplotlib -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='3.20.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
scipy -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
python==3.6 -> sqlite=3.13
Package python-dateutil conflicts for:
jupyter -> jupyter_console -> prompt_toolkit[version='>=1.0.0,<2.0.0'] -> python-dateutil[version='>=2.1']
matplotlib -> python-dateutil
`

**Comment by araji** [comment]
hit the same issue , any luck getting passed it ?

**Comment by LukasLeonardKoening** [comment]
Same problem. This repo seems to be outdated...

**Comment by yusuf-t** [comment]
Ran into the same issue. Checked the following recommendation/workaround from the knowledge base and it works:
https://knowledge.udacity.com/questions/55633

**Comment by UAnjali** [comment]
Hi,
We hope that the mentioned issue is resolved using the knowledge thread shared.
Thank you
